name: dartz_validators
description: Provides a set of extension methods to validate strings, numbers, iterables and maps
version: 1.0.0
repository: https://github.com/mirkorap/dartz-validators
issue_tracker: https://github.com/mirkorap/dartz-validators/issues

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  credit_card_validator: ^2.0.1
  dartz: ^0.10.1
  email_validator: ^2.1.17
  freezed_annotation: ^2.2.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.4
  lints: ^2.0.1
  test: ^1.24.3
