name: dart_validators
description: Provides a number of functions to validate values
version: 1.0.0
repository: https://github.com/mirkorap/dart-validators
issue_tracker: https://github.com/mirkorap/dart-validators/issues

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  credit_card_validator: ^2.0.1
  dartz: ^0.10.1
  email_validator: ^2.1.17
  freezed_annotation: ^2.2.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  lints: ^2.0.0
  test: ^1.16.0
